services:
  - type: web
    name: air-quality-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://your-api-url.onrender.com

